// constellations.h — GENERATED by tools/gen_stars.py; do not edit.
//
// The same names in the same order as sky::kCons in the device's stars.h.
// The id on the wire is 1-based; 0 means cycle. Pipe-separated because the
// only two consumers — the Home Assistant select and the config page — both
// want to split it, and a 88-entry array of pointers costs more flash than
// the string it points into.
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define SCOPE_CON_COUNT 88
static const char SCOPE_CON_NAMES[] = "Canis Major|Carina|Orion|Centaurus|Scorpius|Auriga|Bootes|Ursa Major|Eridanus|Gemini|Crux|Lyra|Sagittarius|Taurus|Leo|Aquila|Vela|Cygnus|Pegasus|Virgo|Perseus|Canis Minor|Draco|Hydra|Hercules|Cetus|Grus|Lupus|Ophiuchus|Andromeda|Cassiopeia|Aquarius|Lepus|Puppis|Ursa Minor|Pavo|Piscis Austrinus|Serpens|Corvus|Ara|Phoenix|Capricornus|Tra|Pisces|Aries|Cepheus|Libra|Columba|Corona Borealis|Hydrus|Musca|Lynx|Volans|Crater|Monoceros|Corona Australis|Tucana|Cancer|Dorado|Triangulum|Delphinus|Lacerta|Sagitta|Indus|Reticulum|Pictor|Circinus|Cvn|Pyxis|Leo Minor|Scutum|Apus|Camelopardalis|Octans|Chamaeleon|Norma|Equuleus|Telescopium|Coma Berenices|Sculptor|Fornax|Horologium|Microscopium|Caelum|Vulpecula|Antlia|Sextans|Mensa";
