#!/bin/sh
# Build the live viewer. Links the REAL render path and every face, exactly as
# tools/hostsim does, so what the browser draws is what the tube draws.
#
# No sanitizers here, unlike the sizing harness: this one has to keep up with a
# 60Hz page, and ASan's shadow-memory checks on a 40k-dot frame do not.
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$HERE/../.."
SRC="$ROOT/display-teensy/src"
SIM="$ROOT/tools/hostsim"

# Face names come from the BRIDGE's table, which is the one the picker, MQTT
# discovery and the web page already agree on (tools/check_faces.py is what
# proves it still matches the device registry). Generating it here rather than
# keeping a third copy means the viewer cannot drift from the clock.
python3 - "$ROOT/bridge-esp32/src/main.cpp" > "$HERE/names.h" <<'PY'
import re, sys
src = open(sys.argv[1]).read()
body = src.split('static const FaceEntry kFaces[] = {', 1)[1].split('};', 1)[0]
pairs = re.findall(r'\{"([^"]+)"\s*,\s*"([^"]+)"\}', body)
print('// names.h - GENERATED by tools/websim/build.sh from the bridge\'s kFaces[].')
print('// Do not edit; rebuild instead.')
print('#pragma once')
print('static const char* const kNames[][2] = {')
for n, f in pairs:
    print('  {"%s","%s"},' % (n, f))
print('};')
print('static const int kNameCount = %d;' % len(pairs))
PY

CXX="${CXX:-c++}"
$CXX -std=c++17 -O2 -g \
  -DWEBSIM_DIR="\"$HERE\"" \
  -I "$HERE" -I "$SIM" -I "$SIM/fake" \
  -I "$ROOT/display-teensy/include" -I "$ROOT/shared" \
  -o "$HERE/websim" \
  "$HERE/websim.cpp" "$SIM/sim.cpp" "$SIM/seed.cpp" \
  "$SRC/vector.cpp" "$SRC/text.cpp" "$SRC/drawlist.cpp" "$SRC/faces.cpp" \
  "$SRC"/faces_*.cpp \
  "$SRC/gauges.cpp" "$SRC/nowplaying.cpp" "$SRC/hostdata.cpp" "$SRC/zones.cpp" \
  "$SRC/radar.cpp" "$SRC/audiofx.cpp"

echo "built $HERE/websim   (run it, then open http://localhost:8080/)"
