#!/usr/bin/env python3
"""Generate names.h from the BRIDGE's kFaces[] table.

That table is the one the picker, MQTT discovery and the config page already
agree on, and tools/check_faces.py is what proves it still matches the device
registry. Generating from it means the viewer cannot drift from the clock; a
third hand-maintained copy certainly would.
"""
import re
import sys

src = open(sys.argv[1]).read()
body = src.split('static const FaceEntry kFaces[] = {', 1)[1].split('};', 1)[0]
pairs = re.findall(r'\{"([^"]+)"\s*,\s*"([^"]+)"\}', body)

print("// names.h - GENERATED by tools/websim/gen_names.py from the bridge's kFaces[].")
print('// Do not edit; rebuild instead.')
print('#pragma once')
print('static const char* const kNames[][2] = {')
for n, f in pairs:
    print('  {"%s","%s"},' % (n, f))
print('};')
print('static const int kNameCount = %d;' % len(pairs))
